name: attitude_app
description: A Flutter app for Attitude Academy login
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.2
  dio: ^5.4.0
  webview_flutter: ^4.7.0
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#00ACC8"  # RGB(0, 172, 200)
  image: assets/splash_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splash_logo.png
    - assets/app_icon.png
